redis server response of (nil)  causes convert error
as per the redis documentation: "The current score of an element can be retrieved using the ZSCORE command, that can also be used to verify if an element already exists or not."
Since we use this feature, thought I would propose at least this modification.  Not sure how it affects the rest of the library though, nor whether a similar modification needs to be made for the other convert_response methods.

julia> score = zscore(conn,"a", objs[i]["name"])
ERROR: `convert` has no method matching convert(::Type{FloatingPoint}, ::Nothing)
 in float at float.jl:56
 in zscore at /home/ubuntu/.julia/v0.3/Redis/src/client.jl:69

John